title: Aidan Rhianne
logo: "https://github.com/arhianne/arhianne.github.io/blob/master/images/DSC09346%20(1)%20(2).jpg"
description: 
  I am a global citizen who hopes to create forward-thinking cities rooted in inclusivity, sustainability, and digital innovation. Currently a Master of City Planning candidate at the University of Pennsylvania, I am exploring how best to utilize data driven strategies and technology to ensure that our future urban infrastructure empowers social, racial, and environmental justice. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/aidan-rhianne-mclaughlin/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
